<a href="https://colab.research.google.com/github/ShGamer16/PRO-129/blob/main/PRO_129.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

!git clone https://github.com/ShGamer16/PRO128

Cloning into 'PRO128'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), 9.07 KiB | 4.53 MiB/s, done.

In [2]:
import pandas as pd

In [3]:
bright_stars_df = pd.read_csv('/content/PRO128/bright_stars.csv')
dwarf_stars_df = pd.read_csv('/content/PRO128/dwarf_stars.csv')

In [4]:
bright_stars_df.head()

   id       Star_name     Distance Mass Radius Luminosity
0   0             Sun  0.000015813    1      1          1
1   1          Sirius       0008.6  2.1   1.71       25.4
2   2         Canopus         0310   15     71     13,500
3   3  Alpha Centauri       0004.4  1.1    1.2          2
4   4        Arcturus         0037  1.1     26        170

In [5]:
dwarf_stars_df.head()

   id                      Star_name  Distance Mass  Radius
0   0  SDSS J000013.54+255418.6 [de]      46.1   48    0.99
1   1        2MASS J00040288-6410358     192.0   19    1.63
2   2                      LHS 102BC       NaN  NaN     NaN
3   3        2MASS J00242463-0158201      37.7   79    1.09
4   4      2MASS J00250365+4759191AB     143.0  NaN     NaN

In [6]:
dwarf_stars_df = dwarf_stars_df.dropna()

In [7]:
dwarf_stars_df.head()

   id                      Star_name  Distance Mass  Radius
0   0  SDSS J000013.54+255418.6 [de]      46.1   48    0.99
1   1        2MASS J00040288-6410358     192.0   19    1.63
3   3        2MASS J00242463-0158201      37.7   79    1.09
5   5        2MASS J00274197+0503417     236.0   31    1.44
7   7         2MASSW J0030300-145033      87.2   54    0.98

In [14]:
dwarf_stars_df.Mass = dwarf_stars_df.Mass.replace('[^a-zA-Z0-9]', '').astype('float')

In [17]:
dwarf_stars_df['Mass'] = dwarf_stars_df['Mass']*0.000954588

In [18]:
dwarf_stars_df['Radius'] = dwarf_stars_df['Radius']*0.102763

In [20]:
dwarf_stars_df.head()

   id                      Star_name  Distance      Mass    Radius
0   0  SDSS J000013.54+255418.6 [de]      46.1  0.000044  0.010455
1   1        2MASS J00040288-6410358     192.0  0.000017  0.017213
3   3        2MASS J00242463-0158201      37.7  0.000072  0.011511
5   5        2MASS J00274197+0503417     236.0  0.000028  0.015207
7   7         2MASSW J0030300-145033      87.2  0.000049  0.010349

In [21]:
merge_planets = pd.merge(dwarf_stars_df,bright_stars_df,on = 'id')
merge_planets.shape
merge_planets.to_csv('129_final.csv')

In [22]:
from google.colab import files
files.download('129_final.csv')